### ISSUE TITLE
Egypt2005 : hc70 hc71

### ISSUE THREAD

**Issue by robin-wang** [wengxyu1030/DHS-Recode-IV#18]
"variables hv001 hv002 hvidx do not uniquely identify observations in the master data"

**Comment by robin-wang** [comment]
2 variables already exist
    For instance, you requested that variable hm_hc70 be renamed hc70.  hc70 is already
    an existing variable in the data.  The variables you specified that already exist
    are hc70 and hc71.

**Comment by robin-wang** [comment]
@wengxyu1030 Pending discussion and resolution
For Egypt and Madagascar in Recode - IV, the bugs are different from the merge / uniquely identifying ones in other surveys.

In DHS-Recode-IV.do, around lines 370.

We see two sections of code:

capture confirm variable c_hc70 c_hc71 
if _rc == 0 {
rename (c_hc70 c_hc71 ) (hc70 hc71 )
}

capture confirm variable hm_hc70 hm_hc71 
if _rc == 0 {
rename (hm_hc70 hm_hc71 ) (hc70 hc71 )
}

These will rename two sets of variables into hc70 and hc71. However, at least for Egypt and Madagascar, up to this point in programme, both c_hc70/71 and hm_hc70/71 are present; This coexistence therefore creates the following error message. 

"2 variables already exist
For instance, you requested that variable hm_hc70 be renamed hc70. hc70 is already
an existing variable in the data. The variables you specified that already exist
are hc70 and hc71."

**Comment by wengxyu1030** [comment]
Hi Robin, 

Thanks for your question, I can't replicate this warning on my end. The rename should not be conflicting with each other as these are conditional on the data source (signified by the hwlevel in the zsc.dta). 

Basically, the existence of c_hc70 c_hc71 and hm_hc70 hm_hc71 is mutually exclusive. 

Regards, 
Aline
